title: My Music Corner
author: Shwetha Ram
email: shwetharam0407@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Carnatic Vocalist. Disciple of Dr. T S Sathyavathi.

baseurl: /music-corner
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    #github:  jekyll
    #rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
     instagram: shwetha.ram
     linkedin: shwetharam
    # pinterest: jekyll
    # youtube: shwetharam0407
     youtube_channel: UCuuV_zFg_JzugBpUzIW7RPg
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
